### PR TITLE
Fix missing action area on rejoin

### LINKED ISSUE #75: User missing ActionArea after rejoin
After refreshing and rejoining a game, I didn't see any console errors but I was missing the approve/reject buttons I should have seen below the board. Maybe it didn't pass my name into the ActionArea switch case properly.

### PR DESCRIPTION
**Pull request by bbailey27**
Bonus: alert when the room is full so users can see

### CODE REVIEW

File: src/components/PreGame/JoinRoom.jsx [hunk 1]
```diff
@@ -57,7 +57,7 @@ export default class JoinRoom extends React.Component {
 
       const previousRoom = window.localStorage.getItem('room');
       if (res.data.roomList.includes(previousRoom)) {
-        const previousName = window.localStorage.getItem('name');
```
Comment (f3mshep) [inline src/components/PreGame/JoinRoom.jsx:60]: nice find

**Review by f3mshep — APPROVED** [review]
